### ISSUE TITLE
charmrun on multicore builds doesn't consume ++local

### ISSUE THREAD

**Issue by stwhite91** [UIUC-PPL/charm#1801]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/1801*

---
When using a multicore build, charmrun doesn't consume '++local'. I think that it should, since it makes perfect sense and is effectively the default, so we shouldn't let the argument pass through to the application's command line arguments.

We should review other charmrun and runtime commands for this type of behavior. I think we currently only consume things like `++ppn` in SMP builds, though I think we should instead consume them and emit a warning that they are only used in SMP mode. Maybe something to discuss in Core meeting.

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-21 20:55:26*

---
~~https://charm.cs.illinois.edu/gerrit/3758~~ https://github.com/UIUC-PPL/charm/commit/97b607dd128689751416f5f97cdb23c73bf263e6

**Comment by evan-charmworks** [comment]
*Original date: 2018-02-27 22:16:19*

---
> I think we currently only consume things like `++ppn` in SMP builds, though I think we should instead consume them and emit a warning that they are only used in SMP mode.

Done in ~~https://charm.cs.illinois.edu/gerrit/3779~~ https://github.com/UIUC-PPL/charm/commit/b914b0520c3d9a188b67f24a11cc38b6d428d11e

**Comment by stwhite91** [comment]
*Original date: 2018-04-06 19:14:04*

---
I am still seeing ++local not consumed on multicore-darwin-x86_64. It looks like it gets passed through to the RTS which ignores it:

```
$ ./charmrun +p1 ./jacobi +vp8 2 2 2 1 ++local
Running command: ./jacobi +vp8 2 2 2 1 ++local +p1

Charm++: standalone mode (not using charmrun)
Charm++> Running in Multicore mode:  1 threads
Converse/Charm++ Commit ID: v6.8.2-533-g94f49f161
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 unique compute nodes (8-way SMP).
Charm++> cpu topology info is gathered in 0.000 seconds.
WARNING: ++local is a command line argument beginning with a '+' but was not parsed by the RTS.
If any of the above arguments were intended for the RTS you may need to recompile Charm++ with different options.

```

**Comment by evan-charmworks** [comment]
*Original date: 2018-04-06 19:17:34*

---
It looks like the multicore charmrun shell script is only set up to parse arguments until it reaches one that does not begin with +, in this case the name of the program, and then pass the rest to the RTS verbatim. `++local` before that point should be consumed correctly.

**Comment by stwhite91** [comment]
*Original date: 2018-04-06 19:22:01*

---
Yikes, that's correct, it works if ++local comes before the program's name.
