### ISSUE TITLE
Windws builds: don't pollute /usr/bin

### ISSUE THREAD

**Issue by jcphill** [UIUC-PPL/charm#574]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/574*

---
Currently unix2nt_cc, unix2nt_ar, and createlink.exe are copied in to /usr/bin when building on Windows.  This makes it impossible to simultaneously perform 64-bit and 32-bit builds on the same machine, and also requires write access to /usr/bin for the building user to perform non-simultaneous builds.  It seems like these binaries could be quite reasonably installed in the, e.g., multicore-win64/bin/ directory along with charmc, charmxi.exe, etc. with only a small modification to the Windows conv-mach.sh files.  You could also rename the commands to not reference Windows NT.

**Comment by mprobson** [comment]
*Original date: 2014-11-04 22:03:24*

---
I've starting implementing a change to fix this. I've just acquired access to cs-dexterity to test. This will be pushed to gerrit soon and then tested.

**Comment by mprobson** [comment]
*Original date: 2014-11-06 06:34:48*

---
Preliminary changes pushed to Gerrit, see here: [[http://charm.cs.uiuc.edu/gerrit/#/c/423/]]

Basically had to modify any place that pointed to unix2nt_*. This still needs to be tested for a fresh install and the files need to be renamed.

**Comment by mprobson** [comment]
*Original date: 2014-11-06 19:47:50*

---
Latest patch set (5) from the earlier gerrit set works on cs-dexterity. Just needs to be merged.

**Comment by PhilMiller** [comment]
*Original date: 2014-11-09 16:43:59*

---
As I understand, the currently merged change is broken. We should try to get that fixed before the core meeting this week. If that schedule isn't doable, then we should retarget this for a later release.

**Comment by mprobson** [comment]
*Original date: 2014-11-09 20:49:04*

---
I plan to have this done by core but I have a few tasks to take care of beforehand. Phil and I already outlined a plan of attack that should work but it still needs to be implemented (it's fairly straightforward though).

**Comment by mprobson** [comment]
*Original date: 2014-11-12 06:53:01*

---
I have implemented a different fix to achieve this feature. I've moved the copying portion of the code from build and into the Makefile after the binary directory is created. I'm waiting to push this fix until I hear back about the write place on where to push this code (previous gerrit issue or a new one; do we need to revert older change; etc). 

I still need to test whether a make clean && make basic still works and also whether win32 and win64 actually play nice now. I should also try builds other than multicore, likely net.

**Comment by mprobson** [comment]
*Original date: 2014-11-12 07:10:19*

---
Changes pushed to gerrit at: [[http://charm.cs.uiuc.edu/gerrit/#/c/431/]]

**Comment by jcphill** [comment]
*Original date: 2014-11-13 03:47:33*

---
Still broken - missing semicolons after commands before escaped newlines.

**Comment by mprobson** [comment]
*Original date: 2015-08-17 21:04:38*

---
I looked back at this bug and saw some comments in redmine: http://charm.cs.uiuc.edu/gerrit/#/c/423/

Seems like this needs more work, or at the very least to be evaluated to ensure it's correct

**Comment by PhilMiller** [comment]
*Original date: 2016-09-07 20:21:49*

---
The win32 build targets are now all gone, so that part is moot.

The change linked above plus ~~https://charm.cs.illinois.edu/gerrit/#/c/431/~~ https://github.com/UIUC-PPL/charm/commit/6d152e60e8612951056703c421698e58b8d82551 move the relevant binaries from /usr/bin, so that's done.

The naming complaint is separate bug #617, linked above.

Thus, closing as fix Merged.
