### ISSUE TITLE
lb_test gives seg fault in multicore build

### ISSUE THREAD

**Issue by bilgeacun** [UIUC-PPL/charm#769]
*Original issue: https://charm.cs.illinois.edu/redmine/issues/769*

---
In multicore-linux64 build, doing a make test on tests/charm++/load_balancing/lb_test gives seg fault at the exit.

Stack trace:
```
TIME PER STEP	80	1.168167	0.006833
TIME PER STEP	90	1.216015	0.047848
All done
[Partition 0][Node 0] End of program

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6fec700 (LWP 26316)]
__run_exit_handlers (status=0, listp=0x7ffff73a4688, run_list_atexit=true) at exit.c:50
50	exit.c: No such file or directory.
(gdb) bt
#0  __run_exit_handlers (status=0, listp=0x7ffff73a4688, run_list_atexit=true) at exit.c:50
#1  0x00007ffff7028635 in __GI_exit (status=<optimized out>) at exit.c:100
#2  0x00000000006abf86 in LrtsExit () at machine.c:1826
#3  0x00000000006a727c in ConverseExit () at machine-common-core.c:1352
#4  0x0000000000593f21 in _exitHandler (env=0xb58920) at init.C:600
#5  0x00000000006ae3c4 in CmiHandleMessage (msg=0xb58920) at convcore.c:1633
#6  0x00000000006ae759 in CsdScheduleForever () at convcore.c:1861
#7  0x00000000006ae69c in CsdScheduler (maxmsgs=-1) at convcore.c:1797
#8  0x00000000006a710d in ConverseRunPE (everReturn=0) at machine-common-core.c:1246
#9  0x00000000006a4827 in call_startfn (vindex=0x1) at machine-smp.c:414
#10 0x00007ffff7bc4e9a in start_thread (arg=0x7ffff6fec700) at pthread_create.c:308
#11 0x00007ffff70e038d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#12 0x0000000000000000 in ?? ()

```

**Comment by nikhil-jain** [comment]
*Original date: 2015-08-18 15:21:48*

---
Hopefully, it should be working now. Please test and confirm.

**Comment by bilgeacun** [comment]
*Original date: 2015-08-18 16:20:20*

---
It still fails for me with the latest version of charm, but It only fails once in 4 runs or so. Works most of the time. I'm testing on valor.

**Comment by ericjbohm** [comment]
*Original date: 2015-08-18 22:08:32*

---
It fails for me on the latest version of Charm on about 1 run out of 8, but when it does so, it usually segfaults during startup.  Clearly this is not the same bug.

CharmLB> Load balancer assumes all CPUs are same.
make: *** [test] Segmentation fault (core dumped)
